# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: zuj-backend-lab-db-1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab
      MYSQL_USER: master_user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    driver: bridge
