# Use root/example as user/password credentials
version: '3.1'

services:
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zuj-migration
    restart: on-failure
    depends_on:
      - db
    environment:
      MYSQL_HOST: zuj-backend-lab-db-1
      MYSQL_PORT: 3306
      MYSQL_USER: master_user
      MYSQL_PASSWORD: password
      MYSQL_DB: lab
    command: yarn migration:run
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zuj-app
    restart: always
    depends_on:
      - db
      - migration
    environment:
      MYSQL_HOST: zuj-backend-lab-db-1
      MYSQL_PORT: 3306
      MYSQL_USER: master_user
      MYSQL_PASSWORD: password
      MYSQL_DB: lab
    command: yarn start
    networks:
      - default
    ports:
      - 3000:3000

  db:
    image: mysql
    container_name: zuj-backend-lab-db-1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab
      MYSQL_USER: master_user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
      - 33060:3306
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    driver: bridge
